config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :argonautes, :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/argonaute.rb
class Argonaute < ApplicationRecord

  scope :gods, -> { where("half_god = true") }
  scope :humans, -> { where("half_god = false") }
  scope :captains, -> { where("captain = true") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/argonautes_controller.rb
class ArgonautesController < ApplicationController

  def create
    @argonaute = Argonaute.new(argonaute_params)
    @argonaute.name = @argonaute.name.split.map(&:capitalize).join(' ')
    @argonautes = Argonaute.all
    @argonaute_name = []
    @argonautes.each do |argonaute|
      @argonaute_name << argonaute.name
    end
    if @argonaute.name == "Jason"
      @argonaute.captain = true
      @argonaute.notes = "beau, vaillant et courageux"
      @argonaute.half_god = true
    end
    if @argonaute_name.include? @argonaute.name
      flash[:alert] = "#{@argonaute.name} est déjà à bord!"
      redirect_to root_path
    elsif @argonautes.size < 50 && @argonaute.save
      flash[:notice] = "#{@argonaute.name} est à bord!"
      redirect_to root_path
    else
      flash[:alert] = "Mollo Jason y a trop de monde à bord!"
      redirect_to root_path
    end
  end

  private

  def argonaute_params
    params.require(:argonaute).permit(:name, :half_god, :notes)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @argonaute = Argonaute.new
    @argonautes = Argonaute.all
    @half_gods = Argonaute.gods
    @humans = Argonaute.humans
    @captains = Argonaute.captains
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheJasonList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

  <!--Titre de la page-->
  <div class="title">
    <h1>La Toison à Jason</h1>

  </div>

  <!-- Bloc capitaine + bloc formulaire-->
  <div class="info d-flex">

    <div class="capitaine section col-md-4">
      <h3> Capitaine de l'Argo:</h3>
      <% if @captains.empty? %>
          <br>
          <br>
          <p>Il manque un capitaine à l'argo!</p>
          <p>Et si on ajoutait Jason?</p>
        <% else %>
        <% @captains.each do |argonaute| %>
          <h2> <%= argonaute.name %> </h2>
          <h3> <%= argonaute.notes %> </h3>
        <% end %>
      <% end %>

    </div>

    <div class="formulaire section col-md-8">
      <div class="form-header">
        <h3><%= @argonautes.size %> /50 Argonautes</h3>
        <% if @argonautes.size >= 50 %>
          <h3> Allons récupérer la TOISON D'OR ! </h3>
        <% end %>

      </div>
      <div class="form-master">
        <%= simple_form_for @argonaute, url: argonautes_path(@argonaute), method: :post, remote: true do |f| %>
        <%= f.input :name, as: :string, required: true, placeholder:"Nom de l'argonaute", label: "Nom" %>
        <%= f.input :half_god, label: "Demi-dieu ?" %>
        <%= f.input :notes, as: :string, required: false, placeholder:"note sur l'argonaute", label: "Note" %>
        <div class="form-button"> <%= f.button :submit, "Aller Hop! Dans l'Argo!", class: "button-form" %> </div>
        <% end %>

      </div>
    </div>

  </div>

  <!-- Bloc capitaine + bloc formulaire-->
  <div class="list d-flex">
    <div class="half-god section col-md-4">
        <h3> Demi-dieux: </h3>
        <% if @half_gods.empty? %>
          <br>
          <br>
          <p> Il nous faudrait un demi-dieu! </p>
          <p> Héraclès n'est pas dispo? </p>
        <% else %>
          <% @half_gods.each do |argonaute| %>
            <p> <%= argonaute.name %> </p>
          <% end %>
        <% end %>
    </div>
    <div class="equipage section col-md-8">
        <h3> Equipage: </h3>
        <% if @humans.empty? %>
          <br>
          <br>
          <p> Il nous faut un équipage ! </p>
          <p> Je suis dispo si besoin :) </p>
        <% else %>
          <div class="equipage-holder d-flex">
            <div class="pair">
              <% @humans.each_with_index do |argonaute, index| %>
                <%if index.even? %>
                 <p> <%= argonaute.name %> </p>
                <% end %>
              <% end %>
            </div>
            <div class="impair">
              <% @humans.each_with_index do |argonaute, index| %>
                <%if index.odd? %>
                  <p> <%= argonaute.name %> </p>
                <% end %>
              <% end %>
            </div>


          </div>
        <%end%>
    </div>

  </div>


  <!--Notification-->
  <div class="message">
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
  </div>

</div>